# Generated by Django 3.2.3 on 2021-07-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=99)),
                ('Autor', models.CharField(max_length=99)),
                ('Sinopsis', models.TextField()),
                ('Precio', models.IntegerField(default=0)),
                ('Stock', models.IntegerField(default=0)),
                ('Publicación', models.DateField()),
            ],
        ),
    ]
